### ISSUE TITLE
TFRecord or H5 export formats

### ISSUE THREAD

**Issue by Mahdi89** [v7labs/darwin-py#111]
Hi, Is there a way to export the annotated datasets in TFRecord or H5 formats?

Please comment on importing such formats as well.

Thanks

**Comment by simedw** [comment]
Hi @Mahdi89 
Sorry for the late reply, I totally missed this message. 

We do currently not support TFRecord nor H5, but it probably wouldn't be too hard to create a converter. 
You can find all our export formats here https://github.com/v7labs/darwin-py/tree/master/darwin/exporter/formats they should be a good starting point.
