### ISSUE TITLE
KeyError: 'status_code' when importing annotations

### ISSUE THREAD

**Issue by zarifaziz** [v7labs/darwin-py#118]
Hi, when running the following command
```
darwin dataset import <dataset-name> coco <coco-file>
```

I got the following error:
```
if res["status_code"] != 200:
KeyError: 'status_code'
```
this means that the key "status_code" doesn't exist in 'res'. 

I have currently implemented a workaround to this on `darwin-py/darwin/importer/importer.py` line 143:
```
if "status_code" in res and res["status_code"] != 200:
```
to ensure that the key exists. Please ensure that the key exists in the importer.py file.

**Comment by simedw** [comment]
Hi @zarifaziz, thanks for bringing this to our attention. 
That issue should be solved in master, we will push a new version soon.
