### ISSUE TITLE
uploading image tags overwrites annotations

### ISSUE THREAD

**Issue by spotiris** [v7labs/darwin-py#124]
I am trying to upload image tags and COCO annotations, so that e.g. multiple images can be grouped by a single tag.
In my use case I have thousands of images which form groups of 6 (XYZ.IJK.jpg, where there are hundreds of XYZ, and 6 IJK).
I want to tag all images which belong to XYZ as "XYZ", and I also need to upload labels to each image.

Currently, if you upload either COCO segmentation annotations (darwin dataset import dataset_name coco coco.json) or csv tags (darwin dataset import dataset_name csv_tags tags.csv) the oldest upload is deleted.
I have modified darwin-py/import/formats/coco.py to simultaneously upload both (see [here](https://github.com/abyss-solutions/darwin-py/blob/master/darwin/importer/formats/coco.py)) but it still overwrites the second lot of annotations.

Is this a bug?
If it is unsupported, I would like to make a feature request to be able to upload both.

**Comment by andreaazzini** [comment]
Hi @spotiris, we've recently introduced an `append` argument you can specify when importing annotations.

```sh
darwin dataset import dataset_name csv_tags tags.csv --append
```

Please, check it out and let us know if that solves your issue.
