### ISSUE TITLE
get_dataset -- Add client configuration directory arg to parameter list

### ISSUE THREAD

**Issue by mexico-johnny** [v7labs/darwin-py#126]
Problem:

The 'get_dataset' function is hardwired via the _load_client() function
to load its config.yml file from a central location (e.g., $HOME/.darwin/config.yml),
which enforces the requirement that consumers/users/projects for a specific user account
are bound to the same configuration. However, there are other use cases where a dedicated
Darwin configuration file (1 per project) would be better suited, thereby allowing each
to control their own configuration needs (i.e. default team, API Key, location of dataset directory).

Example:

projects
├── project-a
 │   └── darwin-config.yml
├── project-b
│   └── darwin-config.yml
└── project-c
    └── darwin-config.yml

Solution:

Add an optional 'config_dir' to the 'get_dataset' function and plumb this parameter  
into the '_load_client' function (also as optional), thereby allowing the '_load_client'
method to either utilize the passed in 'config_dir' parameter to locate its darwin
config.yml configuration file, or to seek out this file in its default location
of $HOME/.darwin/config.yml.

[sample-implementation.zip](https://github.com/v7labs/darwin-py/files/5534449/sample-implementation.zip)

**Comment by andreaazzini** [comment]
Hi @mexico-johnny, this issue is quite old. Apologies for not addressing it in time.

I'm closing it to keep the list of issue fresh, but please do re-open it if you still think this is still relevant, even with the latest version with darwin-py.
