### ISSUE TITLE
Unused dependencies

### ISSUE THREAD

**Issue by bamdadd** [v7labs/darwin-py#144]
Hi 

There are some unused dependencies on your setup.py for example scikit-learn.

This makes darwin-py harder to install since some of these libraries have binary dependencies which effects MacOS installs and local debugging.

If there is no plan to use these libraries can you please remove unused libraries?

**Comment by hajapy** [comment]
This also makes it more difficult to maintain packaging in conda-forge, since we cannot rely on `pip check`, something I noticed while working on packaging it here: https://github.com/conda-forge/staged-recipes/pull/15054

**Comment by simedw** [comment]
`sklearn` is used in `darwin.dataset.utils` but it's wrapped in `try ... except ImportError` and only used when splitting datasets, so I think we can safely remove it from the main setup.py. 

Any other packages that are causing issues?

**Comment by hajapy** [comment]
The other packages I did not find in use were: docutils, factory_boy, and sh. 

You could consider defining optional dependencies using extras_require (eg. for the training functionality).
