### ISSUE TITLE
Uploading Polygons and Tags using Python Library

### ISSUE THREAD

**Issue by swelchm** [v7labs/darwin-py#152]
## Context
Hello, I'm working on programmatically uploading a data set to Darwin that already has both "Classification" and "Polygon" labels using the Darwin Python Library. I'm using the `coco` format to upload polygon labels:

```python
parser=dict(formats.supported_formats)['coco']
importer.import_annotations(dataset, parser, annotation_paths)
 ```

## Issue
The problem here is that my dataset also has tags. Some images are just tagged some are tagged and have polygons, some just have polygons. I'm able to upload tags using the `csv_tags` parser format:

```python
tags_parser=dict(formats.supported_formats)['csv_tags']
importer.import_annotations(dataset, tags_parser, [data_dir/'test_tags.csv'])
```

The problem is that when I upload tags, my polygon annotations get wiped out. It's like I have a `POST`, but really need a `PATCH` method here. Is there a work around? I'm wondering if I can upload tags in the `coco` format in "one go" maybe?

**Comment by andreaazzini** [comment]
Hi @swelchm, we've recently introduced an `append: bool` argument you can pass to `import_annotations`. When set to `True`, the new annotations you import will not overwrite the already existing ones.
