### ISSUE TITLE
Dataset pull raises OSError: [Errno 39] Directory not empty in some cases

### ISSUE THREAD

**Issue by tkupek** [v7labs/darwin-py#153]
We are scheduling lots of trainings on different Linux machines. Each training starts with a dataset pull of darwin-py.
In most cases, this works fine.

However, there are some rare cases where darwin fails to pull the latest version:
```
File "/root/.clearml/venvs-builds/3.8/task_repository/swarm-dnn.git/dataloader/preloader/darwin_loader.py", line 39, in preload_dataset
ds.pull(release=release)
File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/darwin/dataset/remote_dataset.py", line 235, in pull
shutil.rmtree(annotations_dir)
File "/root/.clearml/venvs-builds/3.8/lib/python3.8/shutil.py", line 719, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/root/.clearml/venvs-builds/3.8/lib/python3.8/shutil.py", line 717, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/swarm/.darwin/swarm-analytics/licenseplate_ocr/releases/2021-04-08/annotations'
```

From my point of view, darwin should sync the dataset version from the server in this step. This is why cleaning this folder manually is not helpful (it would need to download everything again).

Please let me know if you need further information.

**Comment by andreaazzini** [comment]
Hi @tkupek, very sorry for the delay in response here, we typically reply to requests through our main support channel in a matter of hours, but because Github is monitored less frequently, we missed this one.

There have been several updates to our SDK since you reached out, when you try this now, are you still experiencing the reported behaviour?

**Comment by tkupek** [comment]
Will upgrade to `0.6.1` and check it.

**Comment by tkupek** [comment]
Looks good for now. Will reopen if it reappears.

What is the preferred way to report new issues on the `darwin-py` package?
