### ISSUE TITLE
Raise exception on failure of upload

### ISSUE THREAD

**Issue by YousefRabi** [v7labs/darwin-py#220]
It would be nice if we get an exception when status_code != 200 in _import_annotations. This way we can catch the exception and do a retry with backoff on the upload. I'm happy to make a PR?

Line 282 in darwin/importer/importer.py

```
if res.get("status_code") != 200:
    print(f"warning, failed to upload annotation to {id}", res)
```

**Comment by Fl4m3Ph03n1x** [comment]
Hello @YousefRabi and thank you for your patience. 

We have reviewed your suggestion with the team and have taken it into consideration together with our future plans. I am happy to announce that we have picked an implementation for the functionality you asked for and that this will be coming out together with our next feature to annotation imports on Darwin'n next minor release (which will be 0.7.X). 

I will keep you updated in this issue, or if you like you may close it now.

Best regards, 
Wind team, v7labs
