### ISSUE TITLE
Importing annotations on DICOMs requires VideoAnnotation format

### ISSUE THREAD

**Issue by cbare** [v7labs/darwin-py#234]
I pushed some DICOM images into Darwin and was trying to import externally produced polygon annotations using the recipe: [Import Annotations to V7][1]

Since these are single frame images (mammograms), I first tried to import polygon annotations using [ImageAnnotation][2] in Darwin JSON Format. The result I got back was:

```txt
warning, failed to upload annotation to 234038087 {'error': 'Response is not JSON encoded', 'status_code': 500, 'text': 'Something went wrong'}
```

With a little hackery, I was able to collect the following:

```txt
Client get request response (Something went wrong) with unexpected status (500).
Client: (Client(default_team=volpara-science))
Request: (endpoint=/dataset_items/234038081/import, payload={'annotations': [{'annotation_class_id': 105926, 'data': {'polygon': {'path': [{'x': 621.4909206, 'y': 0.0}, {'x': 517.0527928500001, 'y': 114.2340069336}, {'x': 510.2191908, 'y': 140.87745338}, {'x': 517.0527928500001, 'y': 144.67379398}, {'x': 531.617465808, 'y': 141.2915814004}, {'x': 615.4855541999999, 'y': 92.56033072}, {'x': 656.2115906939999, 'y': 56.8056493992}, {'x': 661.7337276000001, 'y': 37.4097750222}, {'x': 654.0717942, 'y': 6.55585699614}]}}}]})
[ERROR 500] Something went wrong
```

I was able to import the polygon annotations by switching to [VideoAnnotation][3] format, which I suppose is fair enough since DICOM supports multiframe images.

Issues:

- document that DICOMs must be annotated with [VideoAnnotation][3].
- fix server-side error handling to return better error messages rather than 500 "Something went wrong"
- fix client-side error handling to show response.text if not response.json()

I hope this feedback helps and thanks for a very handy product! 😀

[1]: https://docs.v7labs.com/recipes/import-annotations-to-v7
[2]: https://docs.v7labs.com/reference/darwin-json#imageannotation
[3]: https://docs.v7labs.com/reference/darwin-json#videoannotation

**Comment by Fl4m3Ph03n1x** [comment]
Hello @cbare . With the recent updates to our documentation we made sure to add a warning message to all the places where annotations are imported, making sure our users know that DICOM files should be annotate with VideoAnnotations:
- https://docs.v7labs.com/docs/import-1
- https://docs.v7labs.com/docs/import-annotations-made-outside-of-v7
- https://docs.v7labs.com/recipes

We deeply appreciate the patience you had regarding this issue and truly appreciate that you took the time to report it. 
I will now close this ticket, but feel free to re-open it if you have further questions.

Best regards, 
Wind Team, V7
