### ISSUE TITLE
missing assignment of `parsed_files = imported_files` in else block.

### ISSUE THREAD

**Issue by saadjaved14** [v7labs/darwin-py#267]
missing assignment of `parsed_files = imported_files` in else block.

_Originally posted by @saadjaved14 in https://github.com/v7labs/darwin-py/pull/258#r741361496_

**Comment by Fl4m3Ph03n1x** [comment]
Hello @saadjaved14 
Could you let us know what issue this is causing?

That PR was part of a fix. Please let us know if you found something.

**Comment by saadjaved14** [comment]
Hello @Fl4m3Ph03n1x 

While importing CSV tag (single tag per image) from a file, the annotations are loaded in `imported_files` but not in `parsed_files`. 
Without this assignment, the annotations never make it to the next part of the code and log an error that it can not import due to missing annotations. 

```
warning, failed to upload annotation to 209263511 {'errors': {'annotations': ["can't be blank"]}}
```
