### ISSUE TITLE
Errors in dataset.split()

### ISSUE THREAD

**Issue by ijanerik** [v7labs/darwin-py#273]
In the dataset.split() functions are some errors which I want to highlight.

The code I am using is:
```
client = Client.local()
dataset = client.get_remote_dataset("DATASET_NAME")
dataset.pull()
dataset.split()
```

First of all the default variable name of split() for the `val_percentage` parameter is `0.1`. This results in an error, because the validation on the numbers is based on percentages, so this should be `10`. 

Additionally when the `test_percentage` parameter is `0`, this results in an error, because somewhere in the code the indices of these sets are concatenated, but `0` results in a `None` instead of a list.

Error resulted from `test_percentage=0`:
```
~/miniconda3/envs/birds/lib/python3.9/site-packages/darwin/dataset/split_manager.py in stratified_split(annotation_path, splits, annotation_files, val_percentage, test_percentage, stratified_types, split_seed)
    184         )
    185 
--> 186         stratified_indices = train_indices + val_indices + test_indices
    187         for idx in range(dataset_size):
    188             if idx in stratified_indices:

TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by Fl4m3Ph03n1x** [comment]
Hello @ijanerik 

Thank you for reporting this issue to us. We will look into it and fix it as soon as our pipeline allows it.

Best regards, 
Wind Team, V7
