### ISSUE TITLE
I could not import coco format json. it seems that coco.py has a bug.

### ISSUE THREAD

**Issue by NikaMasa51** [v7labs/darwin-py#278]
I found a bug in coco.py that is used importing json files with coco format.
around 90s rows, when the situation that make_polygon function is called, there is no bouunding_box instance.
so, I put some codes to make dict which has bounding box information('x', 'y', 'w', 'h') .
it seems good.
I m glad for you to refer to this.
please check it. 

![image](https://user-images.githubusercontent.com/48128380/142368061-87d598f8-7c5b-4e2a-9d05-268821bc8c9f.png)

**Comment by Fl4m3Ph03n1x** [comment]
Hello @NikaMasa51, 

Thank you for reporting the issue. We are currently working on a fix for coco imports that should solve your issue:
https://github.com/v7labs/darwin-py/pull/279

Once the fix merged we will make a new release.
So once this ticket closes, all you need to do is to update your darwin-py version to the latest and the issue should be solved.

Best regards, 
Wind Team V7
