### ISSUE TITLE
ValueError: Multiple tags defined for this image 

### ISSUE THREAD

**Issue by amandalucasp** [v7labs/darwin-py#286]
I'm trying to load a dataset on torch using the following code, darwin.__version__ = '0.5.20'. I've tried installing the most up to date version on the conda environment I'm using but was not able to do so.

```
from darwin.torch import get_dataset
dataset_id = dataset_name
dataset = get_dataset(dataset_id, dataset_type="classification")
```
I'm getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/suporte/anaconda3/envs/dino-paws/lib/python3.6/site-packages/darwin/torch/dataset.py", line 99, in __getitem__
    target = self.get_target(index)
  File "/home/suporte/anaconda3/envs/dino-paws/lib/python3.6/site-packages/darwin/torch/dataset.py", line 112, in get_target
    raise ValueError(f"Multiple tags defined for this image ({tags}). This is not supported at the moment.")
```

But apparently there is support for multi-label classification (https://github.com/v7labs/darwin-py/blob/4648116003ac45d87eda5d0722544799fc9eb9a7/darwin/torch/dataset.py#L140) on the current version. Any suggestions on the easiest way to solve this? I'm trying to install darwin==0.7.0 using pip in the anaconda env but I am also getting some erros 

```
  File "<stdin>", line 1, in <module>
  File "/home/suporte/anaconda3/envs/dino-paws/lib/python3.6/site-packages/darwin/__init__.py", line 4, in <module>
    from .client import Client  # noqa
  File "/home/suporte/anaconda3/envs/dino-paws/lib/python3.6/site-packages/darwin/client.py", line 23, in <module>
    class Client:
  File "/home/suporte/anaconda3/envs/dino-paws/lib/python3.6/site-packages/darwin/client.py", line 34, in Client
    ) -> Union[Any, requests.Response]:
AttributeError: module 'requests' has no attribute 'Response'
```

**Comment by Fl4m3Ph03n1x** [comment]
Hello @amandalucasp and thank you for contacting with us. 

I see you are using Python 3.6 and while we officially support it for now, we will stop doing so in December this year when that version of the language looses official support. 

I also understand you have 2 main issues:
- You cannot install the latest version of darwin-py 
- You would like to have multi-label classification but it is not possible

I recommend we first get an stable installation of the latest version of Darwin-py and then move to the second issue.
With this in mind I suggest you create a fresh conda env with Python 3.7 and go with the default recommended installation for torch with conda:

```
conda create -n myenv python=3.7
conda activate myenv
conda config --env --add channels pytorch
conda install pytorch torchvision torchaudio cpuonly
pip install darwin-py
```

Please let me know if this solves the first issue. I will consult with the team regarding the second one. 

Best regards,
V7 Wind Team

**Comment by Fl4m3Ph03n1x** [comment]
Since several days have passed without a reply, I will assume the issue was solved in the meantime. 

Thank you for contacting us and do no hesitate to re-open the issue if you feel like you need further help.

Best regards,
V7 Wind Team
