### ISSUE TITLE
Handling of erroneous json annotation

### ISSUE THREAD

**Issue by edwardwterry** [v7labs/darwin-py#302]
Thank you for putting together such a good tool. I have recently been uploading my own annotations, via a custom YOLO .txt to Darwin .json converter. I got this error periodicially while trying to upload my dataset.

`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://darwin.v7labs.com/api/dataset_items/267804819/import`

I discovered that it was because some of my original annotations had a 0 height or width, which was being (correctly) converted to .json but fell down at the upload stage. Is this something that is worth checking for? If I wanted to try to make a pull request to fix this, where would such an error be handled?

**Comment by andreaazzini** [comment]
Hi @edwardwterry!

Thank you for your words about darwin-py!

Difficult to tell what's wrong with your annotation from what you've posted. I would suggest to contact support, and share your annotation there, so we can try and point you to the right direction.

With that said, we are working on making darwin-py more descriptive of this kind of validation errors, so stay tuned for later updates!

Best

Andrea
