### ISSUE TITLE
Remove unused requests_toolbelt requirement?

### ISSUE THREAD

**Issue by hajapy** [v7labs/darwin-py#311]
AFAICT, requests_toolbelt is not used anywhere, yet it exists in the install_requires.

https://github.com/v7labs/darwin-py/blob/878e9a0d639d6b70886bb53b00486908c3b6a14b/setup.py#L32

https://github.com/v7labs/darwin-py/search?q=requests_toolbelt

**Comment by Fl4m3Ph03n1x** [comment]
Hello @hajapy and thank you for your comment.
We will evaluate this situation and remove the dependency if that is the case. 

Best regards and happy holidays, 
Wind V7 team.
