### ISSUE TITLE
when importing annotations, parser was not made correctly

### ISSUE THREAD

**Issue by NikaMasa51** [v7labs/darwin-py#323]
When I try to import my annotation file (coco format) according to the recipe in the documentation, I get an error.
It happened when creating the parser variable.
Perhaps there is a problem with the formats.supported_formats object.

![スクリーンショット 2022-01-05 17 50 31](https://user-images.githubusercontent.com/48128380/148188568-6253993f-2484-46d7-af59-f26621e490ca.png)
![スクリーンショット 2022-01-05 17 52 34](https://user-images.githubusercontent.com/48128380/148188743-d94b0058-5a99-4a30-8953-7e6c8cf0899a.png)

**Comment by andreaazzini** [comment]
Hi @NikaMasa51,

Thank you for reporting the issue. It was something we were aware of, and promptly fixed.

We have in fact released a new version of darwin-py today (`v0.7.4`), that introduces `get_importer` and `get_exporter` functions for you to use to import or export annotations.

https://pypi.org/project/darwin-py/0.7.4/
https://github.com/v7labs/darwin-py/releases/tag/v0.7.4

You can use it by replacing your line 16 with
```python
parser = get_importer(FORMAT_NAME)
```

Make sure to first import `get_importer` with
```python
from darwin.importer import get_importer
```

We have updated our documentation to reflect these changes:
https://dash.readme.com/project/v7/v1.0/docs/import-annotations-made-outside-of-v7
https://docs.v7labs.com/recipes/import-annotations-to-v7

We are closing this issue, but feel free to re-open it should you have any further issues.

Best

Andrea
