### ISSUE TITLE
darwin.importer.formats.supported_formats can not be converted to dict anymore

### ISSUE THREAD

**Issue by jellevankerk** [v7labs/darwin-py#324]
hi, 

i updated the darwin-py from 0.7.1 to 0.7.4

```python
from darwin.importer import formats
format_name = 'darwin'
parser = dict(formats.supported_formats)[format_name]
```

In 0.7.1 this code worked fine but in 0.7.4 it gives the following error
```
Exception has occurred: ValueError
dictionary update sequence element #0 has length 4; 2 is required
```

formats.supported_formats changed from list with tuples to a list. for me this was a breaking change. 

would you suggest that i change my code or are you planning to revert this change?

**Comment by Fl4m3Ph03n1x** [comment]
Hello @jellevankerk  and thank you for reporting this issue. 

We made this breaking change consciously a few releases ago, so I suggest you update your code. 

Darwin-py is still in its early stages, so breaking changes to the API are expected with new releases as we mature the project and evolve it to meet our client's needs.

However, we also understand the inconvenience this can cause to our users so we will keep this in mind for future releases to avoid problems.

Thank you for your time,
Best Regards, V7 Win Team.
