### ISSUE TITLE
fetch_remote_files not working for spaces (or maybe commas) in filenames

### ISSUE THREAD

**Issue by jbencook** [v7labs/darwin-py#357]
I'm pretty sure there's an issue with the `fetch_remote_files()` method on the `RemoteDataset` class (or more more likely in the actual API call) with either spaces or commas inside filenames.

To reproduce: upload two files to a dataset with filenames `Video Sep 09, 10 02 59 AM.mov` and `5897.mp4` respectively

`dataset.fetch_remote_files({"filenames": ["5897.mp4"]}))` returns results whereas `dataset.fetch_remote_files({"filenames": ["Video Sep 09, 10 02 59 AM.mov"]}))` does not.

**Comment by Fl4m3Ph03n1x** [comment]
Hello @jbencook and thank you for reporting.

Darwin-py currently parses file names using `,` as a separator. Therefore we don't allow `, ` to be in filenames. 
We understand this information is not visible in a user friendly manner and will work on the documentation to make it clear.

Best regards, 
Wind Team, V7

**Comment by Fl4m3Ph03n1x** [comment]
Hello @jbencook , after careful consideration and some internal discussions, we decided to change this unintuitive behaviour. 
As of the last release, v 0.7.10, we now allow files with commas. 

https://github.com/v7labs/darwin-py/releases/tag/v0.7.10

I hope you enjoy the new version as much as we enjoyed upgrading it!
Best regards, 
Wind Team, V7

**Comment by jbencook** [comment]
That's great news -- thank you!
