### ISSUE TITLE
darwin dataset delete-files returns success when deleteing non-existent files

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [v7labs/darwin-py#381]
Current behavior
------

When running the `darwin dataset delete-files` on a dataset for a file that does NOT exist in the dataset, the current behavior is as follows:

```
darwin dataset delete-files cars mycar.jpg -y
Files successfully deleted!
```

Expected behavior
--------------------

I defend the expected behavior should be:
 - A warning telling the user he mentioned a file that does no exist
 - Skip trying to delete the non-existing file
 - If no files were deleted, print a message saying that (probably a warning) instead of a success message.

@andreaazzini and @simedw , do you agree with my expectations?

**Comment by andreaazzini** [comment]
@Fl4m3Ph03n1x thanks for opening this issue. Yes, I agree with your expectations.
