### ISSUE TITLE
Upload video with non integer native frame rate

### ISSUE THREAD

**Issue by marno1d** [v7labs/darwin-py#392]
I would like to upload a video with a non integer (i.e. 29.97) frame rate. In the web interface, there is an option to use the native frame rate. Using this option allows you to annotate every frame in the video. Using the python api, you can specify the frame rate using the fps argument. However, fps is supposed to be an integer according to the [function definition](https://github.com/v7labs/darwin-py/blob/e5f81bf4a4140ed903ae376b5729131fcf04e6b6/darwin/dataset/remote_dataset.py#L118).

`def push(
        self,
        files_to_upload: Optional[List[Union[PathLike, LocalFile]]],
        *,
        blocking: bool = True,
        multi_threaded: bool = True,
        fps: int = 0,
        as_frames: bool = False,
        files_to_exclude: Optional[List[PathLike]] = None,
        path: Optional[str] = None,
        preserve_folders: bool = False,
        progress_callback: Optional[ProgressCallback] = None,
        file_upload_callback: Optional[FileUploadCallback] = None,
    )`

I would like there to be an option to use the native frame rate from the api.

**Comment by Fl4m3Ph03n1x** [comment]
Hello @marno1d and thank you for your post.

Have you tried using the `native` option from the `darwin dataset push` command from the CLI?
https://docs.v7labs.com/docs/import

I believe this could be what you are looking for. 

Please let me know if this helped you.
Best Regards
V7 Wind Team

**Comment by Fl4m3Ph03n1x** [comment]
Hello @marno1d since you have not reply and 7 days have passed, I will assume the issue was solved. 
If this was not the case, please feel free to reopen the ticket. 

Best regards, 
V& Wind Team
