### ISSUE TITLE
Dataset splitting fails due to "least populated class"

### ISSUE THREAD

**Issue by ck37** [v7labs/darwin-py#406]
Hello,

I've been analyzing a dataset and when pulling an updated version I now can no longer split the dataset using the darwin CLI. I receive this error:

```
Error: The least populated class in y has only 1 member, which is too few. The 
minimum number of groups for any class cannot be less than 2.
```

However none of the classes has a single member - the lowest is 29. This dataset combines bounding boxes with classification tags though - is it looking at all combinations of labels? If so, is it possible for the error message to display what combination is causing the error? Or simply coarsen the stratification?

**Comment by ck37** [comment]
I think the issue would be resolved if the CLI allowed specifying the "stratified_types" argument to [split_dataset](https://github.com/v7labs/darwin-py/blob/master/darwin/dataset/split_manager.py#L78), and I could specify "bounding_box" so that the tag is not also used for stratification.

**Comment by Fl4m3Ph03n1x** [comment]
Hello @ck37 , 

Could you provide us with a sample dataset so our support team can look into your issue? 

Best regards, 
V7 Wind team

**Comment by owencjones** [comment]
@ck37 I'm closing this as it's become stale.  However, if you're still having issues, feel free to either open a new bug, or email us.
