### ISSUE TITLE
darwin dataset set-status will not complain if given file does not exist.

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [v7labs/darwin-py#407]
The command:

```
darwin dataset set-file-status dataset-demo new 134.tifffdfsdfsfsfd
```

Will give the same output as:

```
darwin dataset set-file-status dataset-demo clear 134.tif
```

The first one is clearly wrong and tries to act upon a file that does not exist. The second command works. 
We need to fix this bug so a message is print when a file that does not exist is detected.

**Comment by owencjones** [comment]
Closing as internal and not planned
