### ISSUE TITLE
Uploading a COCO format json with "attributes" defined in it for each annotation doesn't appear in the platform. 

### ISSUE THREAD

**Issue by francozacco** [v7labs/darwin-py#412]
Hi everyone, I'm submitting this issue because I downloaded a `coco.json` from the platform which had a series of attributes for each annotation defined. So under the "extra" key of each annotation, I have
```json
"extra": {"attributes": ["some-attribute", "some-other-attribute"]}
```
but then after downloading the COCO formatted json I wanted to re-upload the same file to another dataset I created with the same images and the attributes defined previously don't appear in the platform anymore for this new dataset.
All the classes and segmentation masks seem to be uploaded correctly.

**Comment by andreaazzini** [comment]
Hi @francozacco, thank you for opening this issue.

I will make sure this is ticketed, so we can work on a fix ASAP.
In the meantime, let us know if you are keen on fixing this issue on your personal fork of darwin-py, and I can sync with you to can open a PR and add in your contribution!

Cheers,
Andrea

**Comment by francozacco** [comment]
Hi @andreaazzini, yes I'll be working on a solution on my personal fork, would love to open a PR as soon as I have a fix to add my contribution.

Cheers,
Franco.

**Comment by francozacco** [comment]
Hello @andreaazzini I started this PR [https://github.com/v7labs/darwin-py/pull/413](https://github.com/v7labs/darwin-py/pull/413) to fix this, let me know what you think. Thank you.

Cheers,
Franco.

**Comment by francozacco** [comment]
@andreaazzini  any news about this? The solution as I mentioned above can be found [here](https://github.com/v7labs/darwin-py/pull/413).
Cheers,
Franco.

**Comment by owencjones** [comment]
As the PR, before the repo had a dedicated maintainer, fell behind master and is now closed, I can only close this with my apologies.

I am implementing a better system for highlighting github bugs to the internal team.

Owen V7
