### ISSUE TITLE
Sort filenames in darwin.utils.find_files

### ISSUE THREAD

**Issue by SimJeg** [v7labs/darwin-py#414]
Hello,

I want to programmatically push a dataset to Darwin using the `RemoteDataset.push` method. For my use case I need to both keep the directory structure (kwarg `preserve_folders=True`) and to keep the order of the files within each sub-directories (in my case 3 consecutive images per sub-directory).

The push method calls the `darwin.utils.find_files` function which does not sort the results of the different `Path.glob` calls. I made this simple modification to solve my issue (line 207): 

```python
# Before
return [f for f in found_files if f not in map(Path, files_to_exclude)]
```

```python
# After 
return sorted([f for f in found_files if f not in map(Path, files_to_exclude)])
```

If you think it is relevant, this could be added in a future release.

**Comment by owencjones** [comment]
As this is very old, and predates my time with the company, I'm closing as stale, but if anyone wants to reopen with a use case, or open a PR, then I'm happy to reopen.
