### ISSUE TITLE
No such file or directory - exporting annotations

### ISSUE THREAD

**Issue by ChristofferEdlund** [v7labs/darwin-py#438]
When running the **darwin convert coco <src> <dest>** command pointing to a folder that does not exists, the program throws an error instead of generating the specified directory.

This might be low priority, but it should be relatively easy to generate target directory.

![image](https://user-images.githubusercontent.com/18189030/188585772-806ca4ae-6876-4be5-921b-e4d983f6055f.png)

**Comment by owencjones** [comment]
This should now be addressed @ChristofferEdlund.  Let me know on here or slack if you see recurrances.
