### ISSUE TITLE
Would it be possible to get new transforms support at darwin/torch/transforms.py?

### ISSUE THREAD

**Issue by martluide** [v7labs/darwin-py#474]
Hi,

Not sure how to best make this request, but would it be possible to get more transform support at darwin/torch/transforms.py? This would significantly extend the usability of the package as a whole as best-in-class training uses transforms and other data manipulation methods to better train models. Without them, the alternative is to work around Darwin or to try and hack them together.

I would really like it if you could do RandomRotation, RandomAdjustSharpness, GaussianBlur, Resize or other popular transforms. If there was a way to make the entire torchvision.transforms.transforms compatible it would be lovely. I would love to have just a few more transforms to begin with, of course it would be great to have more and even compatibility with the popular Albumentations library.

Is there a way to hack the current library with some of these transformations that I am just not aware of? I would really appreciate any support.

Best,
Mart

**Comment by owencjones** [comment]
Hi Mart,

Thanks for your request, and apologies that it wasn't responded to faster.  I see that you've also spoken to our customer support team on a couple of occasions, and I'm working on implementing a system that will information across github issues and our own ticketing systems in house.

I will add a feature request ticket to our backlog and make the product managers aware of it, and close this issue for now, but also, depending how you use `darwin-py` you may find it possible to pass your transform in.

Both our `get_dataset` method, and our Pytorch Datasets of each type (ClassificationDataset, InstanceSegmentationDataset, etc.) support passing an optional `transform` property that is then applied on the `__getitem__` dunder method.  So you should be able to pass transforms to this.

I haven't tried this myself, but Torchvision transforms are supposed to work already, so let me know if you hit issues, but 🤞🏻 it works for you straight off.

Thanks

Owen
