### ISSUE TITLE
Upgrading jsonschema to 4.x

### ISSUE THREAD

**Issue by rmax** [v7labs/darwin-py#478]
Hi all,

Since version `0.7.16`, `jsonschema` [has been pinned to 3.2.0](https://github.com/v7labs/darwin-py/commit/3c57d6622ba5b6fc41babf4a2629c1157e74c7ac) which causes a version conflict with other package ([asdf](https://github.com/asdf-format/asdf/blob/master/pyproject.toml#L23)) in our stack that relies on `jsonschema>=4.0`.

Is it possible to upgrade `jsonschema` to `4.x` or is there a major blocker in Darwin's API or backend?

**Comment by morincl** [comment]
I have created a pull request that could solve your issue: https://github.com/v7labs/darwin-py/pull/477

**Comment by bonnie-chow** [comment]
Hey any update on this?

**Comment by rmax** [comment]
@bonnie-chow waiting feedback from darwin devs https://github.com/v7labs/darwin-py/pull/477#issuecomment-1297047057

**Comment by Nathanjp91** [comment]
This should be getting resolved soon with addition of jsonschema validation feature currently in QA seen [here](https://github.com/v7labs/darwin-py/pull/508)

**Comment by rmax** [comment]
Solved in latest release 🎉
