### ISSUE TITLE
Why is the background class removed in LocalDataset?

### ISSUE THREAD

**Issue by hwaxxer** [v7labs/darwin-py#526]
I haven't debugged this fully but I believe this breaks your torch datasets. For example the `SemanticSegmentationDataset` will not contain the `__background__` class and so when the mask is constructed, the first class (not `__background__`) of the dataset will have `category_id==0`, which is the same as background.

Line in question:
https://github.com/v7labs/darwin-py/blob/master/darwin/dataset/local_dataset.py#L91

**Comment by Nathanjp91** [comment]
@hwaxxer I believe this is resolved with the latest release and [PR 543](https://github.com/v7labs/darwin-py/pull/543). Closing this issue, if the problem persists let us know.
