### ISSUE TITLE
How to use Python code to convert the color map of an image into paired like v7 annotation platform on web?

### ISSUE THREAD

**Issue by FrebEaton** [v7labs/darwin-py#625]
I want to write my own code to convert the color scheme of an image to Paired color scheme on the v7 platform. I have tried many methods, but none of them can achieve the same effect as on the v7 annotation website. I would like to know how the v7 annotation platform converts the color scheme of an image to Paired color scheme? Can this library achieve the effect?

**Comment by owencjones** [comment]
Hi,

Whilst we do deal with colour palettes for images, this is largely surrounding the processing of image semantic maps, and we don't have a built in feature for converting colour schemes for you.

If you want to write your own, the main tools we use for these tasks are [Pillow](https://pypi.org/project/Pillow/) and [Numpy](https://pypi.org/project/numpy/)

If you create functionality you'd like added to the project, feel free to fork it, and open a pull request.

Many thanks

Owen
