### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by filippocastelli** [v7labs/darwin-py#683]
Dependency  specifications in  pyproject.toml exclude `python 3.11.x`.
This means we can't install `darwin-py` using poetry in our latest 3.11-based products, considering that no particularly deep issues emerge in #651 we install it install separately using pip. 

Support for python 3.11 would be very desirable now that most libraries tend to support it as well.

**Comment by Nathanjp91** [comment]
@owencjones The major problem was that it would require updates from Torch 1.x -> 2.0, but Jon has checked out that particular library update and has let me know that there's no backwards comparability issues and has tested that with the models code. We could merge in 3.11 support soon.

**Comment by frerksaxen** [comment]
We plan to move to python3.11 soon and would really appreciate if this could be prioritized. Thanks.
