### ISSUE TITLE
pillow 10.x support

### ISSUE THREAD

**Issue by filippocastelli** [v7labs/darwin-py#684]
10.x versions of PIL are unsupported in your pyproject.toml poetry specifications, this tends to create dependency issues with recent packages.

It would be useful to have PIL 10.x support

**Comment by owencjones** [comment]
I will raise a ticket to try this and ensure it works - if it does, I see no reason not to do this.

**Comment by owencjones** [comment]
@filippocastelli As an update, this is ticketed, and will be assigned to sprint

**Comment by JBWilkie** [comment]
Hi @filippocastelli I apologise for the delayed response here, but darwin-py uses PIL 10.x from 0.8.54 onward!
