### ISSUE TITLE
Issue with importing COCO format segmentations

### ISSUE THREAD

**Issue by ishaanmht** [v7labs/darwin-py#687]
name: Issue with importing coco format segmentations
description: get support with the issue of importing segmentations.
title: "Issue with importing COCO format segmentations "
labels: ["Issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: mehtaishaan4@gmail.com
    validations:
      required: false
  - type: textarea
    id: I am facing issues while importing segmentations using command line tools. Please see screenshots and relevant files in attachments.
    attributes:
      label: What happened?
      description: I expected to import my prior segmentations to v7 platform but I am having issues with CLI tools to upload the segmentation.
      placeholder: Refer to attached screenshots.
    validations:
      required: true
  - type: textbox
    id: version
    attributes:
      label: What version of darwin-py were you using?
      description: Run darwin-py --version at command line and paste the output here
![Screenshot 2023-10-13 at 5 16 02 PM](https://github.com/v7labs/darwin-py/assets/47014106/519855fb-7c85-48df-9290-985dacf34198)
![Screenshot 2023-10-13 at 5 16 18 PM](https://github.com/v7labs/darwin-py/assets/47014106/30f7f800-ea41-4abe-9d3b-3f64a5b4e06a)

    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

**Comment by JBWilkie** [comment]
Hi @ishaanmht

Apologies for the significant delay here, and thanks for standing by! Unfortunately our support team would need to investigate this issue first. You can reach them at support@v7labs.com and they'll respond to you promptly!
