### ISSUE TITLE
Got " ITEM_COUNT_LIMIT_EXCEEDED" when there's no file in my V7 repository

### ISSUE THREAD

**Issue by Coronal-Halo** [v7labs/darwin-py#711]
When I try to upload files using "darwin dataset push" command, I got " files couldn't be uploaded because an error occurred" with Reason being " ITEM_COUNT_LIMIT_EXCEEDED". However, I do not have anything in my remote repository since I just deleted my last dataset a few hours ago. I also got the same error trying to manually upload my images on the V7 website, the error was "ignoring X files above the limit" with 'X' being the number of images I was trying to upload. How do I solve this problem?

**Comment by JBWilkie** [comment]
Hello!

The reason you're encountering this error is that there is a 100 file limit for teams on our Free plan. This includes files that have been deleted. As such, I don't believe this is an issue with darwin-py.

If you have any questions related to the product you can always post in our Community: https://v7-community.circle.so/home
