### ISSUE TITLE
version missing in dataset.get_release(version) NotFound exception

### ISSUE THREAD

**Issue by frerksaxen** [v7labs/darwin-py#713]
Hi,

great API! Could you please print the release name parameter when raising an exception in
`darwin/dataset/remote_dataset.py", line 693, in get_release`?

When I use a valid dataset slug but with an invalid version, it will not print the version but the slug.
It would be great if the requested version would also show up in the error message.

Keep up the good work!

**Comment by JBWilkie** [comment]
Hi @frerksaxen I apologise for the delay!

Thank you for raising this. A solution has been implemented in the [DAR-2275 branch](https://github.com/v7labs/darwin-py/tree/DAR-2275). I will let you know when a release goes out including this fix!

**Comment by JBWilkie** [comment]
Hi @frerksaxen a fix for this is now available in the latest release (0.8.61). Let us know if you run into any more issues!
