### ISSUE TITLE
darwin authenticate cli arguments

### ISSUE THREAD

**Issue by frerksaxen** [v7labs/darwin-py#714]
Hi.

Currently, `darwin authenticate` requires you to manually type the team name and the datasets_dir.
I would like to automate pulling datasets from within CI/CD pipelines.
Could you please add the team name and the datasets directory as two additional cli arguments?
e.g. like so: `darwin authenticate --datasets_dir ~/my_default_ataset_directory --default_team my_default_team_name`
This would not require any breaking change for you and it would make live much easier for me.

**Comment by Nathanjp91** [comment]
This seems reasonable. I'll add in a PR later today.

**Comment by frerksaxen** [comment]
Thanks! Exactly what I was looking for. Do you already know when this is part of a new version of darwin-py? My entire team is waiting for it. :)

**Comment by Nathanjp91** [comment]
Hey, sorry for the wait. We've had some lower capacity the last few weeks and priorities were shifted. This should be merged in the latest release.
