### ISSUE TITLE
No function named get_dataset

### ISSUE THREAD

**Issue by TDYbrownrc** [v7labs/darwin-py#72]
Looking in your torch integration API, I don't see a function called "get_dataset()", which is suggested for us to use on the PyTorch integration Readme. It was supposed to be in datasets.py, but it isn't in that file. Is that function missing?

**Comment by almazan** [comment]
Hi @TDYbrownrc, some recent changes in the way local datasets work made obsolete some of the util functions in `darwin.torch`. `get_dataset()` was moved to `darwin.dataset` and broke the old way to load Pytorch's dataloaders. We're working on a fix (together with an updated README) and will upload it as soon as possible.

**Comment by almazan** [comment]
Hi @TDYbrownrc, sorry for the delay. Just to let you know, a new version of darwin-py that fixes the issue with `get_dataset()` is already available. Here's an example of how to use it:

```python
from darwin.dataset.utils import split_dataset
from darwin.torch import get_dataset
import darwin.torch.transforms as T

split_dataset("/datasets/bird-species", val_percentage=20, test_percentage=0)

trfs_train = T.Compose([T.RandomHorizontalFlip(), T.ToTensor()])
db_train = get_dataset("/datasets/bird-species", dataset_type="instance_segmentation", \
    partition="train", split_type="stratified", transform=trfs_train)
```

You can find a detailed explanation in the README.
