### ISSUE TITLE
Pulling an export is slow

### ISSUE THREAD

**Issue by jwmetrifork** [v7labs/darwin-py#815]
I find myself waiting for hours at a time for the dataset to be pulled. 
I've tried both the CLI command and also the python library, both are pulling the data to slowly.

**Comment by JBWilkie** [comment]
Hi @jwmetrifork thanks for getting in touch! Unfortunately, this issue would need to be tackled first by our support team. Please get in touch with them at support@v7labs.com with as many details about the slowness you're experiencing, and they'll respond to you promptly!
