### ISSUE TITLE
ValidationError : 1 validation error for SelectedProperty frame_index

### ISSUE THREAD

**Issue by AntoninLem** [v7labs/darwin-py#837]
Hello,
I'm using darwin-py version 0.8.59, and when I pull the dataset with darwin-py, I encounter this error.

![image](https://github.com/v7labs/darwin-py/assets/61834560/96d6ae50-43af-4a94-af0d-5d37f91b6fed)

**Comment by JBWilkie** [comment]
Hi @AntoninLem thanks for getting in touch! A solution to this has been implemented in the [DAR-1562 branch](https://github.com/v7labs/darwin-py/tree/DAR-1562) with [this PR](https://github.com/v7labs/darwin-py/pull/825). It will be going out with the next release. As soon as it's available I'll notify you!

**Comment by JBWilkie** [comment]
Hi @AntoninLem a fix for this is now available from versions 0.8.60 onward!
