### ISSUE TITLE
New metadata.json breaking annotation pulling

### ISSUE THREAD

**Issue by rob-safi** [v7labs/darwin-py#842]
when pulling a dataset a new `.v7/metadata.json` now appears in the annotation folder.

This breaks functions like `local_dataset.get_annotation_filepaths()`
due to: return (str(e) for e in sorted(annotations_dir.glob("**/*.json"))) matching `metadata.json`

I think all
```
annotations_dir.glob("**/*.json")
```

need to be changed to something like
```
[
      annotation_path
      for annotation_path in annotations_dir.rglob("*.json")
      if annotation_path.stem != "metadata"
  ]
```

**Comment by JBWilkie** [comment]
Hi @rob-safi thanks for getting in touch! A solution to this has been implemented in the [DAR-1679 branch](https://github.com/v7labs/darwin-py/tree/DAR-1679) with [this PR](https://github.com/v7labs/darwin-py/pull/823). It will be going out with the next release. I will notify you when it's available!

**Comment by JBWilkie** [comment]
Hi @rob-safi, you should find that the newest release of darwin-py (0.8.60) contains a fix for this issue! Please give it a go, and let us know if you run into any more problems.
