### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'

### ISSUE THREAD

**Issue by styxofsyntax** [v7labs/darwin-py#893]
When installing darwin-py in a miniconda virtual env.

os: Ubuntu 24.04 LTS
python: 3.12.4
pip: 24.1.2
conda: 24.5.0

Followed this [solution](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) but still getting the same error.

I have tried:
- Updating pip to the latest version.
- Creating a fresh conda virtual env.
- Running the following commands.

```bash
pip install darwin-py
```

```bash
python -m ensurepip --upgrade
python -m pip install --upgrade setuptools
python -m pip install darwin-py
```

```bash
python3.12 -m ensurepip --upgrade
python3.12 -m pip install --upgrade setuptools
python3.12 -m pip install darwin-py
```

**Comment by JBWilkie** [comment]
Hi @styxofsyntax, thanks for raising this! Unfortunately, dariwn-py doesn't support Python 3.12 yet. Currently supported versions are `<3.12, >=3.8.0`. The supported Python versions of the latest release will always be available on [PyPi](https://pypi.org/project/darwin-py/).
