### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by SteffenCzolbe** [v7labs/darwin-py#902]
darwin-py is the last package in my ML environment that is not supporting python 3.12. Can this be updated?

**Comment by filippocastelli** [comment]
we're having the same issue, we'd like to move our dev environments to 3.12 but `darwin-py`  doesn't support it

**Comment by nrudakov** [comment]
Python 3.13 is released, so its support could also be added

**Comment by Inquisitive-ME** [comment]
Still an issue when will this be fixed?

**Comment by JBWilkie** [comment]
Hi all, apologies for the delay. Support for Python 3.12 is scheduled to be completed in the next few weeks. This will also involve dropping support for 3.8. I'll post back here when there's an update.

**Comment by JBWilkie** [comment]
Hi all, version 1.1.0 is now released with support for Python 3.12. Unfortunately, we were unable to add support for Python 3.13 in the same release due to issues with some dependencies and Python 3.13

We'll be able to revisit 3.13 in the future!
